### test index
GET http://localhost:9090
Cache-Control: no-cache

### test sign up
POST http://localhost:9090/api/sign-up
Content-Type: application/json

{
    "username": "Noah1",
    "email": "Noah1@gmail.com",
    "password": "123456",
    "workspace": "Noah1"
}

### test sign in
# @name signin
POST http://localhost:9090/api/sign-in
Content-Type: application/json

{
    "email": "Noah@gmail.com",
    "password": "123456"
}

###

@token = {{signin.response.body.data.token}}

### test get user list
GET http://localhost:9090/api/user/list
Cache-Control: no-cache
Authorization: Bearer {{ token }}

### test create chat
POST http://localhost:9090/api/chat/create
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "name": "Noah1",
    "user_ids": [1, 2]
}

### test get chat list
GET http://localhost:9090/api/chat/list
Cache-Control: no-cache
Authorization: Bearer {{ token }}

### test get chat detail
GET http://localhost:9090/api/chat/7
Cache-Control: no-cache
Authorization: Bearer {{ token }}
